// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhMkj9vZV6R5bS0RXeLo4YYcVjK-Rim3g',
    appId: '1:391307996951:web:ef6526ab3efbedfe065152',
    messagingSenderId: '391307996951',
    projectId: 'phone-store-ae5d0',
    authDomain: 'phone-store-ae5d0.firebaseapp.com',
    storageBucket: 'phone-store-ae5d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVMi9WKx-EYA-fMMUl4Ah9cr0MvKU22BQ',
    appId: '1:391307996951:android:bd6b897aa4b2a3ab065152',
    messagingSenderId: '391307996951',
    projectId: 'phone-store-ae5d0',
    storageBucket: 'phone-store-ae5d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4Wf4rHqtm3_zgs5rgXcc3YIyX75Xd5c',
    appId: '1:391307996951:ios:9f39c0eee0aac346065152',
    messagingSenderId: '391307996951',
    projectId: 'phone-store-ae5d0',
    storageBucket: 'phone-store-ae5d0.firebasestorage.app',
    iosBundleId: 'com.phoneStore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo4Wf4rHqtm3_zgs5rgXcc3YIyX75Xd5c',
    appId: '1:391307996951:ios:9f39c0eee0aac346065152',
    messagingSenderId: '391307996951',
    projectId: 'phone-store-ae5d0',
    storageBucket: 'phone-store-ae5d0.firebasestorage.app',
    iosBundleId: 'com.phoneStore.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhMkj9vZV6R5bS0RXeLo4YYcVjK-Rim3g',
    appId: '1:391307996951:web:f3c9e29e2ee9e971065152',
    messagingSenderId: '391307996951',
    projectId: 'phone-store-ae5d0',
    authDomain: 'phone-store-ae5d0.firebaseapp.com',
    storageBucket: 'phone-store-ae5d0.firebasestorage.app',
  );
}
